name: CI/CD for NodeJS App
'on':
  push:
    branches:
      - main
jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version:
          - 22.x
    steps:
      - uses: actions/checkout@v4
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'npm'
      - name: Perform Application Check
        run: |
          npm ci
          npm run build --if-present
      - name: Run Code Coverage
        run: | 
          npm run check
      - name: Upload Coverage report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./test-reports/
          if-no-files-found: error  
